//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core;
using Domain.Core.Specification;
using Domain.MainModules.Entities;
using System.Collections.Generic;

namespace Domain.MainModule.Contracts
{
    public interface ITBL_Admin_UsuariosRepository : IRepository<TBL_Admin_Usuarios>
    {
        /// <summary>
        /// Retorna el objeto usuario con informacion asociada de la tabla roles.
        /// </summary>
        /// <param name="specification"></param>
        /// <returns></returns>
        TBL_Admin_Usuarios RetornarUsuarioConRoles(ISpecification<TBL_Admin_Usuarios> specification);

      
        /// <summary>
        /// Obtiene el usuario filtrado por ID
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        TBL_Admin_Usuarios GetUsuarioById(int id);

     

        /// <summary>
        /// RETORNA LISTADO DE USUARIOS CON ROLES
        /// </summary>
        /// <param name="specification"></param>
        /// <returns></returns>
        List<TBL_Admin_Usuarios> RetornarUsuariosConRoles(ISpecification<TBL_Admin_Usuarios> specification);

        /// <summary>
        /// Obtiene el usuario filtrado por el nombre
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        TBL_Admin_Usuarios GetUsuarioByName(string name);

      
    }
}
    