//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System.Data.Objects;
using Infraestructure.Data.Core;
using Domain.MainModules.Entities;

namespace Infrastructure.Data.MainModule.UnitOfWork
{
    
    ///<sumary>
    ///Base contract for context in Main Module 
    ///</sumary>
    
    public interface IMainModuleUnitOfWork :IQueryableUnitOfWork
    {
       
        #region ObjectSet Properties
    
        IObjectSet<AlarmasCompromiso> AlarmasCompromiso{get;}
        
    
        IObjectSet<AnexosComentarioRespuesta> AnexosComentarioRespuesta{get;}
        
    
        IObjectSet<Bloques> Bloques{get;}
        
    
        IObjectSet<Campos> Campos{get;}
        
    
        IObjectSet<ComentariosRespuesta> ComentariosRespuesta{get;}
        
    
        IObjectSet<Compromisos> Compromisos{get;}
        
    
        IObjectSet<Contratos> Contratos{get;}
        
    
        IObjectSet<Dependencias> Dependencias{get;}
        
    
        IObjectSet<DocumentosAnexoContrato> DocumentosAnexoContrato{get;}
        
    
        IObjectSet<DocumentosContrato> DocumentosContrato{get;}
        
    
        IObjectSet<DocumentosRadicado> DocumentosRadicado{get;}
        
    
        IObjectSet<Empresas> Empresas{get;}
        
    
        IObjectSet<EntregablesANHCompromiso> EntregablesANHCompromiso{get;}
        
    
        IObjectSet<EstadosAccion> EstadosAccion{get;}
        
    
        IObjectSet<Fases> Fases{get;}
        
    
        IObjectSet<FormatosIndice> FormatosIndice{get;}
        
    
        IObjectSet<Localizaciones> Localizaciones{get;}
        
    
        IObjectSet<LogAuditoria> LogAuditoria{get;}
        
    
        IObjectSet<LogContratos> LogContratos{get;}
        
    
        IObjectSet<ManualAnh> ManualAnh{get;}
        
    
        IObjectSet<Monedas> Monedas{get;}
        
    
        IObjectSet<NovedadesContrato> NovedadesContrato{get;}
        
    
        IObjectSet<NovedadesFase> NovedadesFase{get;}
        
    
        IObjectSet<PagosObligaciones> PagosObligaciones{get;}
        
    
        IObjectSet<Parametros> Parametros{get;}
        
    
        IObjectSet<Pozos> Pozos{get;}
        
    
        IObjectSet<Radicados> Radicados{get;}
        
    
        IObjectSet<TBL_Admin_ModuleRepository> TBL_Admin_ModuleRepository{get;}
        
    
        IObjectSet<TBL_Admin_ModuleService> TBL_Admin_ModuleService{get;}
        
    
        IObjectSet<TBL_Admin_ModuleType> TBL_Admin_ModuleType{get;}
        
    
        IObjectSet<TBL_Admin_ModuleVersion> TBL_Admin_ModuleVersion{get;}
        
    
        IObjectSet<TBL_Admin_Modulos> TBL_Admin_Modulos{get;}
        
    
        IObjectSet<TBL_Admin_OpcionesMenu> TBL_Admin_OpcionesMenu{get;}
        
    
        IObjectSet<TBL_Admin_OptionList> TBL_Admin_OptionList{get;}
        
    
        IObjectSet<TBL_Admin_Roles> TBL_Admin_Roles{get;}
        
    
        IObjectSet<TBL_Admin_Secciones> TBL_Admin_Secciones{get;}
        
    
        IObjectSet<TBL_Admin_TypeByModules> TBL_Admin_TypeByModules{get;}
        
    
        IObjectSet<TBL_Admin_Usuarios> TBL_Admin_Usuarios{get;}
        
    
        IObjectSet<TBL_ModuloDocumentosAnexos_Carpetas> TBL_ModuloDocumentosAnexos_Carpetas{get;}
        
    
        IObjectSet<TBL_ModuloDocumentosAnexos_Documento> TBL_ModuloDocumentosAnexos_Documento{get;}
        
    
        IObjectSet<Terceros> Terceros{get;}
        
    
        IObjectSet<TiposContrato> TiposContrato{get;}
        
    
        IObjectSet<TiposPagoObligacion> TiposPagoObligacion{get;}
        

        #endregion
    
    }
}
	
