//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una plantilla T4 de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  Abril 24 de 2012.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 
using System;
using System.Collections.Generic;
using System.Linq;
using Applications.MainModule.Admin.IServices;
using Applications.MainModule.Admin.Resources;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Domain.MainModule.Contracts;

namespace Applications.MainModule.Admin.Services
{
    public class SfTBL_Admin_RolesManagementServices : ISfTBL_Admin_RolesManagementServices
    {

         #region Fields
         readonly ITBL_Admin_RolesRepository _tblAdminRolesRepository;
         #endregion

         #region Constructor
         /// <summary>
         /// Constructor de la Calse 
         /// </summary>
         public SfTBL_Admin_RolesManagementServices( ITBL_Admin_RolesRepository tblAdminRolesRepository)
         {
            if (tblAdminRolesRepository == null)
                throw new ArgumentNullException("tblAdminRolesRepository");
            _tblAdminRolesRepository = tblAdminRolesRepository;
         }
         #endregion

         #region Members
         /// <summary>
         /// Crea una nueva instancia de la entidad 
         /// </summary>
         public TBL_Admin_Roles NewEntity()
         {
            return new TBL_Admin_Roles();
         }

         /// <summary>
         /// Inserta un nuevo registro en la Base de Datos.
         /// </summary>
         public void Add(TBL_Admin_Roles entity)
         {
            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblAdminRolesRepository.UnitOfWork;
            _tblAdminRolesRepository.Add(entity);
            //Complete changes in this unit of work
            unitOfWork.Commit();
         }

          /// <summary>
          /// Actualiza el registro en la Base de Datos.
          /// </summary>
         public void Modify(TBL_Admin_Roles entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Modificar : El objeto esta nulo."));

            var unitOfWork = _tblAdminRolesRepository.UnitOfWork;
            _tblAdminRolesRepository.Modify(entity);
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Elimina el registro en la Base de Datos.
          /// </summary>
         public void Remove(TBL_Admin_Roles entity)
         {
            if (entity == null)
                throw new ArgumentNullException(string.Format("Eliminar : El objeto esta nulo."));

            //Begin unit of work ( if Transaction is required init here a new TransactionScope element
            var unitOfWork = _tblAdminRolesRepository.UnitOfWork;

            _tblAdminRolesRepository.Remove(entity);

            //Complete changes in this unit of work
            unitOfWork.CommitAndRefreshChanges();
         }

          /// <summary>
          /// Obtiene una única entidad filtrada por ID.
          /// </summary>
         public TBL_Admin_Roles FindById(int id)
         {
            if (id == 0)
                throw new ArgumentNullException(string.Format("Busqueda por Id : El parametro es nulo."));

            Specification<TBL_Admin_Roles> specification = new DirectSpecification<TBL_Admin_Roles>(u => u.IdRol == id);

            return _tblAdminRolesRepository.GetEntityBySpec(specification);
           
         }

       
          /// <summary>
          /// Obtiene el listado de entidades activas.
          /// </summary>
         public List<TBL_Admin_Roles> FindBySpec(bool isActive)
         {
            Specification<TBL_Admin_Roles> specification = new DirectSpecification<TBL_Admin_Roles>(u => u.Activo == isActive);
            return _tblAdminRolesRepository.GetBySpec(specification).ToList();
         }

       

        /// <summary>
          /// Obtiene el listado de entidades activas y paginadas.
          /// </summary>
         public List<TBL_Admin_Roles> FindPaged(int pageIndex, int pageCount)
         {
            if (pageIndex < 0)
                throw new ArgumentException(Messages.exception_InvalidPageIndex, "pageIndex");

            if (pageCount <= 0)
                throw new ArgumentException(Messages.exception_InvalidPageCount, "pageCount");


            Specification<TBL_Admin_Roles> onlyEnabledSpec = new DirectSpecification<TBL_Admin_Roles>(u => u.Activo);

            return _tblAdminRolesRepository.GetPagedElements(pageIndex, pageCount, u => u.IdRol, onlyEnabledSpec, true).ToList();
         }


         public TBL_Admin_Roles FindRoleByName(string name)
         {
             Specification<TBL_Admin_Roles> onlyEnabledSpec = new DirectSpecification<TBL_Admin_Roles>(u => u.Activo && u.NombreRol.Equals(name));

             return _tblAdminRolesRepository.GetEntityBySpec(onlyEnabledSpec);
         }

        public int CountByFilter(string role)
        {
            Specification<TBL_Admin_Roles> onlyEnabledSpec = new DirectSpecification<TBL_Admin_Roles>(u => u.Activo);
            if (!string.IsNullOrEmpty(role))
            {
                var id = Convert.ToInt32(role);
                onlyEnabledSpec &= new DirectSpecification<TBL_Admin_Roles>(r => r.IdRol == id);
            }

            return _tblAdminRolesRepository.GetBySpec(onlyEnabledSpec).Count();
        }

        public IEnumerable<TBL_Admin_Roles> FindRoleByFilter(string role, int currentPage, int pageZise)
        {
            Specification<TBL_Admin_Roles> onlyEnabledSpec = new DirectSpecification<TBL_Admin_Roles>(u => u.Activo);
            if(!string.IsNullOrEmpty(role))
            {
                var id = Convert.ToInt32(role);
                onlyEnabledSpec &= new DirectSpecification<TBL_Admin_Roles>(r => r.IdRol ==  id);
            }

            return _tblAdminRolesRepository.GetPagedElements(currentPage, pageZise, u => u.IdRol, onlyEnabledSpec, true).ToList();
        }

        #endregion

         #region IDisposable Members

        /// <summary>
        /// Release all resources
        /// </summary>
        public void Dispose()
        {
            //release used unit of work
            //if you have many repositories but  lifetime is per resolve only need
            //dispose one

            if (_tblAdminRolesRepository != null)
            {
                _tblAdminRolesRepository.UnitOfWork.Dispose();
            }
        }

        #endregion
    }
}
    