//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using Domain.Core.Entities;

namespace Domain.MainModules.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TBL_Admin_ModuleType))]
    [KnownType(typeof(TBL_Admin_Modulos))]
    
    public partial class TBL_Admin_TypeByModules: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int OID
        {
            get { return _oID; }
            set
            {
                if (_oID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'OID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _oID = value;
                    OnPropertyChanged("OID");
                }
            }
        }
        private int _oID;
    
        [DataMember]
        public Nullable<int> IdModulo
        {
            get { return _idModulo; }
            set
            {
                if (_idModulo != value)
                {
                    ChangeTracker.RecordOriginalValue("IdModulo", _idModulo);
                    if (!IsDeserializing)
                    {
                        if (TBL_Admin_Modulos != null && TBL_Admin_Modulos.IdModulo != value)
                        {
                            TBL_Admin_Modulos = null;
                        }
                    }
                    _idModulo = value;
                    OnPropertyChanged("IdModulo");
                }
            }
        }
        private Nullable<int> _idModulo;
    
        [DataMember]
        public int IdModuleType
        {
            get { return _idModuleType; }
            set
            {
                if (_idModuleType != value)
                {
                    ChangeTracker.RecordOriginalValue("IdModuleType", _idModuleType);
                    if (!IsDeserializing)
                    {
                        if (TBL_Admin_ModuleType != null && TBL_Admin_ModuleType.IdModuleType != value)
                        {
                            TBL_Admin_ModuleType = null;
                        }
                    }
                    _idModuleType = value;
                    OnPropertyChanged("IdModuleType");
                }
            }
        }
        private int _idModuleType;
    
        [DataMember]
        public string Titulo
        {
            get { return _titulo; }
            set
            {
                if (_titulo != value)
                {
                    _titulo = value;
                    OnPropertyChanged("Titulo");
                }
            }
        }
        private string _titulo;
    
        [DataMember]
        public bool MostrarTitulo
        {
            get { return _mostrarTitulo; }
            set
            {
                if (_mostrarTitulo != value)
                {
                    _mostrarTitulo = value;
                    OnPropertyChanged("MostrarTitulo");
                }
            }
        }
        private bool _mostrarTitulo;
    
        [DataMember]
        public int position
        {
            get { return _position; }
            set
            {
                if (_position != value)
                {
                    _position = value;
                    OnPropertyChanged("position");
                }
            }
        }
        private int _position;
    
        [DataMember]
        public string Placeholder
        {
            get { return _placeholder; }
            set
            {
                if (_placeholder != value)
                {
                    _placeholder = value;
                    OnPropertyChanged("Placeholder");
                }
            }
        }
        private string _placeholder;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;
    
        [DataMember]
        public string CreateBy
        {
            get { return _createBy; }
            set
            {
                if (_createBy != value)
                {
                    _createBy = value;
                    OnPropertyChanged("CreateBy");
                }
            }
        }
        private string _createBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreateOn
        {
            get { return _createOn; }
            set
            {
                if (_createOn != value)
                {
                    _createOn = value;
                    OnPropertyChanged("CreateOn");
                }
            }
        }
        private Nullable<System.DateTime> _createOn;
    
        [DataMember]
        public string ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                if (_modifiedBy != value)
                {
                    _modifiedBy = value;
                    OnPropertyChanged("ModifiedBy");
                }
            }
        }
        private string _modifiedBy;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                if (_modifiedOn != value)
                {
                    _modifiedOn = value;
                    OnPropertyChanged("ModifiedOn");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedOn;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TBL_Admin_ModuleType TBL_Admin_ModuleType
        {
            get { return _tBL_Admin_ModuleType; }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_ModuleType, value))
                {
                    var previousValue = _tBL_Admin_ModuleType;
                    _tBL_Admin_ModuleType = value;
                    FixupTBL_Admin_ModuleType(previousValue);
                    OnNavigationPropertyChanged("TBL_Admin_ModuleType");
                }
            }
        }
        private TBL_Admin_ModuleType _tBL_Admin_ModuleType;
    
        [DataMember]
        public TBL_Admin_Modulos TBL_Admin_Modulos
        {
            get { return _tBL_Admin_Modulos; }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_Modulos, value))
                {
                    var previousValue = _tBL_Admin_Modulos;
                    _tBL_Admin_Modulos = value;
                    FixupTBL_Admin_Modulos(previousValue);
                    OnNavigationPropertyChanged("TBL_Admin_Modulos");
                }
            }
        }
        private TBL_Admin_Modulos _tBL_Admin_Modulos;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TBL_Admin_ModuleType = null;
            TBL_Admin_Modulos = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupTBL_Admin_ModuleType(TBL_Admin_ModuleType previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TBL_Admin_TypeByModules.Contains(this))
            {
                previousValue.TBL_Admin_TypeByModules.Remove(this);
            }
    
            if (TBL_Admin_ModuleType != null)
            {
                if (!TBL_Admin_ModuleType.TBL_Admin_TypeByModules.Contains(this))
                {
                    TBL_Admin_ModuleType.TBL_Admin_TypeByModules.Add(this);
                }
    
                IdModuleType = TBL_Admin_ModuleType.IdModuleType;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TBL_Admin_ModuleType")
                    && (ChangeTracker.OriginalValues["TBL_Admin_ModuleType"] == TBL_Admin_ModuleType))
                {
                    ChangeTracker.OriginalValues.Remove("TBL_Admin_ModuleType");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TBL_Admin_ModuleType", previousValue);
                }
                if (TBL_Admin_ModuleType != null && !TBL_Admin_ModuleType.ChangeTracker.ChangeTrackingEnabled)
                {
                    TBL_Admin_ModuleType.StartTracking();
                }
            }
        }
    
        private void FixupTBL_Admin_Modulos(TBL_Admin_Modulos previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TBL_Admin_TypeByModules.Contains(this))
            {
                previousValue.TBL_Admin_TypeByModules.Remove(this);
            }
    
            if (TBL_Admin_Modulos != null)
            {
                if (!TBL_Admin_Modulos.TBL_Admin_TypeByModules.Contains(this))
                {
                    TBL_Admin_Modulos.TBL_Admin_TypeByModules.Add(this);
                }
    
                IdModulo = TBL_Admin_Modulos.IdModulo;
            }
            else if (!skipKeys)
            {
                IdModulo = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("TBL_Admin_Modulos")
                    && (ChangeTracker.OriginalValues["TBL_Admin_Modulos"] == TBL_Admin_Modulos))
                {
                    ChangeTracker.OriginalValues.Remove("TBL_Admin_Modulos");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("TBL_Admin_Modulos", previousValue);
                }
                if (TBL_Admin_Modulos != null && !TBL_Admin_Modulos.ChangeTracker.ChangeTrackingEnabled)
                {
                    TBL_Admin_Modulos.StartTracking();
                }
            }
        }

        #endregion
    }
}
