//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presenters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presenters.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are required.
        /// </summary>
        internal static string CamposObligatorios {
            get {
                return ResourceManager.GetString("CamposObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Opción [{0}]  tiene registros relacionados. Elimine primero las opciones que dependan de ésta e intentelo nuevamente..
        /// </summary>
        internal static string ChildNodes {
            get {
                return ResourceManager.GetString("ChildNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not delete the record. Has related data.
        /// </summary>
        internal static string DatosRelacionados {
            get {
                return ResourceManager.GetString("DatosRelacionados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al  eliminar el objeto. Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al descargar el archivo..
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al editar el objeto.  Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string EditError {
            get {
                return ResourceManager.GetString("EditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro [{0}] ya se encuentra registrado en la Base de Datos..
        /// </summary>
        internal static string EntityExist {
            get {
                return ResourceManager.GetString("EntityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must complete sections: [&lt;b&gt;{0}&lt;/b&gt;] to start the publishing process..
        /// </summary>
        internal static string ErrorCompleteSections {
            get {
                return ResourceManager.GetString("ErrorCompleteSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The nit {0} already registered.
        /// </summary>
        internal static string ErrorExistNit {
            get {
                return ResourceManager.GetString("ErrorExistNit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QueryString is null!!!.
        /// </summary>
        internal static string ErrorQueryString {
            get {
                return ResourceManager.GetString("ErrorQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restoring the selected records..
        /// </summary>
        internal static string ErrorRestore {
            get {
                return ResourceManager.GetString("ErrorRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site field does not have the correct format..
        /// </summary>
        internal static string ErrorUrlFormat {
            get {
                return ResourceManager.GetString("ErrorUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must complete some categories missing in action plan..
        /// </summary>
        internal static string ErrorValidacionActionPlan {
            get {
                return ResourceManager.GetString("ErrorValidacionActionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check digit does not match the entered the field.
        /// </summary>
        internal static string ErrorValidacionDigitoChequeo {
            get {
                return ResourceManager.GetString("ErrorValidacionDigitoChequeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue, load the file type associated with the final proposal..
        /// </summary>
        internal static string ErrorValidacionTipoArchivo {
            get {
                return ResourceManager.GetString("ErrorValidacionTipoArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al recuperar el objeto [{0}] desde la Base de Datos. Comuníquese con el Administrador del sistema..
        /// </summary>
        internal static string GetObjectError {
            get {
                return ResourceManager.GetString("GetObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al listar los objetos del tipo [{0}] desde la Base de Datos.
        /// </summary>
        internal static string ListError {
            get {
                return ResourceManager.GetString("ListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a location..
        /// </summary>
        internal static string LocationError {
            get {
                return ResourceManager.GetString("LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal was {0} by the user {1} at {2} in section {3}..
        /// </summary>
        internal static string LogDeCambios {
            get {
                return ResourceManager.GetString("LogDeCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to edit the current record. Note that the changes will be recorded in the system for audit purposes..
        /// </summary>
        internal static string MessageEdit {
            get {
                return ResourceManager.GetString("MessageEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Opción [{0}] ya se encuentra registrada en la Base de Datos. Ingrese una descripción diferente para la opción!!!.
        /// </summary>
        internal static string NodeExist {
            get {
                return ResourceManager.GetString("NodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longitud del password debe ser mayor a 5 caracteres..
        /// </summary>
        internal static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proceso {0} terminó con errores. Verifique el log de procesamiento para ver los detalles del error..
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process completed successfully..
        /// </summary>
        internal static string ProcessOk {
            get {
                return ResourceManager.GetString("ProcessOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal was {0} by the user {1} at {2}..
        /// </summary>
        internal static string ProposalCreatedModified {
            get {
                return ResourceManager.GetString("ProposalCreatedModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposal was changed to state {0} user {1} at {2}.
        /// </summary>
        internal static string ProposalStatusChange {
            get {
                return ResourceManager.GetString("ProposalStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la  manipulación de la Cadena de Consulta. Acceso no autorizado: 401.
        /// </summary>
        internal static string QueryStringError {
            get {
                return ResourceManager.GetString("QueryStringError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycling the customer error. Only customers can recycle draft or published state.
        /// </summary>
        internal static string RecicleCustomer {
            get {
                return ResourceManager.GetString("RecicleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert the object. Contact your system administrator..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al crear la opción.. Debe primero seleccionar un nodo de la lista..
        /// </summary>
        internal static string SelectedNode {
            get {
                return ResourceManager.GetString("SelectedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar por lo menos un registro de la lista {0}.
        /// </summary>
        internal static string SelectedRecors {
            get {
                return ResourceManager.GetString("SelectedRecors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceso denegado al usuario  [{0}]. Comuníquese con el Administrador..
        /// </summary>
        internal static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario [{0}] ya se encuentra registrado en la Base de Datos. Ingrese un nombre de usuario Diferente!!!..
        /// </summary>
        internal static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de lectura del usaurio de Red. Verifique la configuración del Sitio en el ISS y Web.Config de la aplicación..
        /// </summary>
        internal static string UserWindowsError {
            get {
                return ResourceManager.GetString("UserWindowsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} Field  can not be null..
        /// </summary>
        internal static string ValidarCampoNotNull {
            get {
                return ResourceManager.GetString("ValidarCampoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must enter at least one field of the form..
        /// </summary>
        internal static string ValidarCamposNull {
            get {
                return ResourceManager.GetString("ValidarCamposNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected user already assigned as {0}.
        /// </summary>
        internal static string ValidarUsuarioStaff {
            get {
                return ResourceManager.GetString("ValidarUsuarioStaff", resourceCulture);
            }
        }
    }
}
