//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Domain.MainModule.Contracts;
using Infraestructure.Data.Core;
using Infraestructure.Data.Core.Extensions;
using Infrastructure.CrossCutting.Logging;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using Infrastructure.Data.MainModule.Resources;
using Infrastructure.Data.MainModule.UnitOfWork;

namespace Infrastructure.Data.MainModule.Repositories
{
    public class TBL_Admin_ModuleTypeRepository : GenericRepository<TBL_Admin_ModuleType>, ITBL_Admin_ModuleTypeRepository 
    {
        public TBL_Admin_ModuleTypeRepository(IMainModuleUnitOfWork unitOfWork, ITraceManager traceManager) : base(unitOfWork, traceManager)
        {
        }

        /// <summary>
        /// Obtiene el listado de los modulos activos y los servicios relacionados.
        /// </summary>
        /// <param name="specification"></param>
        /// <returns></returns>
        public IEnumerable<TBL_Admin_ModuleType> FindAllModuleType(ISpecification<TBL_Admin_ModuleType> specification)
        {
            //validate specification
            if (specification == null)
                throw new ArgumentNullException("specification");

            var activeContext = UnitOfWork as IMainModuleUnitOfWork;
            if (activeContext != null)
            {
                //perform operation in this repository
                var specific = specification.SatisfiedBy();
                return activeContext.TBL_Admin_ModuleType
                                    .Include(m => m.TBL_Admin_ModuleService)
                                    .Include(m=> m.TBL_Admin_ModuleRepository)
                                    .Where(specific)
                                    .ToList();
            }
            throw new InvalidOperationException(string.Format(
                CultureInfo.InvariantCulture,
                Messages.exception_InvalidStoreContext,
                GetType().Name));
        }
    }
}
    