//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using Domain.Core.Entities;

namespace Domain.MainModules.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TBL_Admin_ModuleRepository))]
    [KnownType(typeof(TBL_Admin_ModuleService))]
    [KnownType(typeof(TBL_Admin_TypeByModules))]
    
    public partial class TBL_Admin_ModuleType: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IdModuleType
        {
            get { return _idModuleType; }
            set
            {
                if (_idModuleType != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdModuleType' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idModuleType = value;
                    OnPropertyChanged("IdModuleType");
                }
            }
        }
        private int _idModuleType;
    
        [DataMember]
        public string Nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("Nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public string NombreEnsamblado
        {
            get { return _nombreEnsamblado; }
            set
            {
                if (_nombreEnsamblado != value)
                {
                    _nombreEnsamblado = value;
                    OnPropertyChanged("NombreEnsamblado");
                }
            }
        }
        private string _nombreEnsamblado;
    
        [DataMember]
        public string NombreClase
        {
            get { return _nombreClase; }
            set
            {
                if (_nombreClase != value)
                {
                    _nombreClase = value;
                    OnPropertyChanged("NombreClase");
                }
            }
        }
        private string _nombreClase;
    
        [DataMember]
        public string path
        {
            get { return _path; }
            set
            {
                if (_path != value)
                {
                    _path = value;
                    OnPropertyChanged("path");
                }
            }
        }
        private string _path;
    
        [DataMember]
        public string PathEdicion
        {
            get { return _pathEdicion; }
            set
            {
                if (_pathEdicion != value)
                {
                    _pathEdicion = value;
                    OnPropertyChanged("PathEdicion");
                }
            }
        }
        private string _pathEdicion;
    
        [DataMember]
        public bool AutoActivar
        {
            get { return _autoActivar; }
            set
            {
                if (_autoActivar != value)
                {
                    _autoActivar = value;
                    OnPropertyChanged("AutoActivar");
                }
            }
        }
        private bool _autoActivar;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;
    
        [DataMember]
        public string CreateBy
        {
            get { return _createBy; }
            set
            {
                if (_createBy != value)
                {
                    _createBy = value;
                    OnPropertyChanged("CreateBy");
                }
            }
        }
        private string _createBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreateOn
        {
            get { return _createOn; }
            set
            {
                if (_createOn != value)
                {
                    _createOn = value;
                    OnPropertyChanged("CreateOn");
                }
            }
        }
        private Nullable<System.DateTime> _createOn;
    
        [DataMember]
        public string ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                if (_modifiedBy != value)
                {
                    _modifiedBy = value;
                    OnPropertyChanged("ModifiedBy");
                }
            }
        }
        private string _modifiedBy;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                if (_modifiedOn != value)
                {
                    _modifiedOn = value;
                    OnPropertyChanged("ModifiedOn");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedOn;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<TBL_Admin_ModuleRepository> TBL_Admin_ModuleRepository
        {
            get
            {
                if (_tBL_Admin_ModuleRepository == null)
                {
                    _tBL_Admin_ModuleRepository = new TrackableCollection<TBL_Admin_ModuleRepository>();
                    _tBL_Admin_ModuleRepository.CollectionChanged += FixupTBL_Admin_ModuleRepository;
                }
                return _tBL_Admin_ModuleRepository;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_ModuleRepository, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_ModuleRepository != null)
                    {
                        _tBL_Admin_ModuleRepository.CollectionChanged -= FixupTBL_Admin_ModuleRepository;
                    }
                    _tBL_Admin_ModuleRepository = value;
                    if (_tBL_Admin_ModuleRepository != null)
                    {
                        _tBL_Admin_ModuleRepository.CollectionChanged += FixupTBL_Admin_ModuleRepository;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_ModuleRepository");
                }
            }
        }
        private TrackableCollection<TBL_Admin_ModuleRepository> _tBL_Admin_ModuleRepository;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_ModuleService> TBL_Admin_ModuleService
        {
            get
            {
                if (_tBL_Admin_ModuleService == null)
                {
                    _tBL_Admin_ModuleService = new TrackableCollection<TBL_Admin_ModuleService>();
                    _tBL_Admin_ModuleService.CollectionChanged += FixupTBL_Admin_ModuleService;
                }
                return _tBL_Admin_ModuleService;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_ModuleService, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_ModuleService != null)
                    {
                        _tBL_Admin_ModuleService.CollectionChanged -= FixupTBL_Admin_ModuleService;
                    }
                    _tBL_Admin_ModuleService = value;
                    if (_tBL_Admin_ModuleService != null)
                    {
                        _tBL_Admin_ModuleService.CollectionChanged += FixupTBL_Admin_ModuleService;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_ModuleService");
                }
            }
        }
        private TrackableCollection<TBL_Admin_ModuleService> _tBL_Admin_ModuleService;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_TypeByModules> TBL_Admin_TypeByModules
        {
            get
            {
                if (_tBL_Admin_TypeByModules == null)
                {
                    _tBL_Admin_TypeByModules = new TrackableCollection<TBL_Admin_TypeByModules>();
                    _tBL_Admin_TypeByModules.CollectionChanged += FixupTBL_Admin_TypeByModules;
                }
                return _tBL_Admin_TypeByModules;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_TypeByModules, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_TypeByModules != null)
                    {
                        _tBL_Admin_TypeByModules.CollectionChanged -= FixupTBL_Admin_TypeByModules;
                    }
                    _tBL_Admin_TypeByModules = value;
                    if (_tBL_Admin_TypeByModules != null)
                    {
                        _tBL_Admin_TypeByModules.CollectionChanged += FixupTBL_Admin_TypeByModules;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_TypeByModules");
                }
            }
        }
        private TrackableCollection<TBL_Admin_TypeByModules> _tBL_Admin_TypeByModules;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TBL_Admin_ModuleRepository.Clear();
            TBL_Admin_ModuleService.Clear();
            TBL_Admin_TypeByModules.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupTBL_Admin_ModuleRepository(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_ModuleRepository item in e.NewItems)
                {
                    item.TBL_Admin_ModuleType = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_ModuleRepository", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_ModuleRepository item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_ModuleType, this))
                    {
                        item.TBL_Admin_ModuleType = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_ModuleRepository", item);
                    }
                }
            }
        }
    
        private void FixupTBL_Admin_ModuleService(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_ModuleService item in e.NewItems)
                {
                    item.TBL_Admin_ModuleType = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_ModuleService", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_ModuleService item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_ModuleType, this))
                    {
                        item.TBL_Admin_ModuleType = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_ModuleService", item);
                    }
                }
            }
        }
    
        private void FixupTBL_Admin_TypeByModules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_TypeByModules item in e.NewItems)
                {
                    item.TBL_Admin_ModuleType = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_TypeByModules", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_TypeByModules item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_ModuleType, this))
                    {
                        item.TBL_Admin_ModuleType = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_TypeByModules", item);
                    }
                }
            }
        }

        #endregion
    }
}
