//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

using Domain.Core.Entities;

namespace Domain.MainModules.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(TBL_Admin_Secciones))]
    [KnownType(typeof(TBL_Admin_OpcionesMenu))]
    [KnownType(typeof(TBL_Admin_TypeByModules))]
    
    public partial class TBL_Admin_Modulos: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IdModulo
        {
            get { return _idModulo; }
            set
            {
                if (_idModulo != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdModulo' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idModulo = value;
                    OnPropertyChanged("IdModulo");
                }
            }
        }
        private int _idModulo;
    
        [DataMember]
        public string NombreModulo
        {
            get { return _nombreModulo; }
            set
            {
                if (_nombreModulo != value)
                {
                    _nombreModulo = value;
                    OnPropertyChanged("NombreModulo");
                }
            }
        }
        private string _nombreModulo;
    
        [DataMember]
        public string Descripcion
        {
            get { return _descripcion; }
            set
            {
                if (_descripcion != value)
                {
                    _descripcion = value;
                    OnPropertyChanged("Descripcion");
                }
            }
        }
        private string _descripcion;
    
        [DataMember]
        public string Imagen
        {
            get { return _imagen; }
            set
            {
                if (_imagen != value)
                {
                    _imagen = value;
                    OnPropertyChanged("Imagen");
                }
            }
        }
        private string _imagen;
    
        [DataMember]
        public string ImageDisabled
        {
            get { return _imageDisabled; }
            set
            {
                if (_imageDisabled != value)
                {
                    _imageDisabled = value;
                    OnPropertyChanged("ImageDisabled");
                }
            }
        }
        private string _imageDisabled;
    
        [DataMember]
        public Nullable<bool> ShowInMenu
        {
            get { return _showInMenu; }
            set
            {
                if (_showInMenu != value)
                {
                    _showInMenu = value;
                    OnPropertyChanged("ShowInMenu");
                }
            }
        }
        private Nullable<bool> _showInMenu;
    
        [DataMember]
        public string PathFormPreView
        {
            get { return _pathFormPreView; }
            set
            {
                if (_pathFormPreView != value)
                {
                    _pathFormPreView = value;
                    OnPropertyChanged("PathFormPreView");
                }
            }
        }
        private string _pathFormPreView;
    
        [DataMember]
        public bool IsActive
        {
            get { return _isActive; }
            set
            {
                if (_isActive != value)
                {
                    _isActive = value;
                    OnPropertyChanged("IsActive");
                }
            }
        }
        private bool _isActive;
    
        [DataMember]
        public string CreateBy
        {
            get { return _createBy; }
            set
            {
                if (_createBy != value)
                {
                    _createBy = value;
                    OnPropertyChanged("CreateBy");
                }
            }
        }
        private string _createBy;
    
        [DataMember]
        public Nullable<System.DateTime> CreateOn
        {
            get { return _createOn; }
            set
            {
                if (_createOn != value)
                {
                    _createOn = value;
                    OnPropertyChanged("CreateOn");
                }
            }
        }
        private Nullable<System.DateTime> _createOn;
    
        [DataMember]
        public string ModifiedBy
        {
            get { return _modifiedBy; }
            set
            {
                if (_modifiedBy != value)
                {
                    _modifiedBy = value;
                    OnPropertyChanged("ModifiedBy");
                }
            }
        }
        private string _modifiedBy;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedOn
        {
            get { return _modifiedOn; }
            set
            {
                if (_modifiedOn != value)
                {
                    _modifiedOn = value;
                    OnPropertyChanged("ModifiedOn");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedOn;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<TBL_Admin_Secciones> TBL_Admin_Secciones
        {
            get
            {
                if (_tBL_Admin_Secciones == null)
                {
                    _tBL_Admin_Secciones = new TrackableCollection<TBL_Admin_Secciones>();
                    _tBL_Admin_Secciones.CollectionChanged += FixupTBL_Admin_Secciones;
                }
                return _tBL_Admin_Secciones;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_Secciones, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_Secciones != null)
                    {
                        _tBL_Admin_Secciones.CollectionChanged -= FixupTBL_Admin_Secciones;
                    }
                    _tBL_Admin_Secciones = value;
                    if (_tBL_Admin_Secciones != null)
                    {
                        _tBL_Admin_Secciones.CollectionChanged += FixupTBL_Admin_Secciones;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_Secciones");
                }
            }
        }
        private TrackableCollection<TBL_Admin_Secciones> _tBL_Admin_Secciones;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_OpcionesMenu> TBL_Admin_OpcionesMenu
        {
            get
            {
                if (_tBL_Admin_OpcionesMenu == null)
                {
                    _tBL_Admin_OpcionesMenu = new TrackableCollection<TBL_Admin_OpcionesMenu>();
                    _tBL_Admin_OpcionesMenu.CollectionChanged += FixupTBL_Admin_OpcionesMenu;
                }
                return _tBL_Admin_OpcionesMenu;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_OpcionesMenu, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_OpcionesMenu != null)
                    {
                        _tBL_Admin_OpcionesMenu.CollectionChanged -= FixupTBL_Admin_OpcionesMenu;
                    }
                    _tBL_Admin_OpcionesMenu = value;
                    if (_tBL_Admin_OpcionesMenu != null)
                    {
                        _tBL_Admin_OpcionesMenu.CollectionChanged += FixupTBL_Admin_OpcionesMenu;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_OpcionesMenu");
                }
            }
        }
        private TrackableCollection<TBL_Admin_OpcionesMenu> _tBL_Admin_OpcionesMenu;
    
        [DataMember]
        public TrackableCollection<TBL_Admin_TypeByModules> TBL_Admin_TypeByModules
        {
            get
            {
                if (_tBL_Admin_TypeByModules == null)
                {
                    _tBL_Admin_TypeByModules = new TrackableCollection<TBL_Admin_TypeByModules>();
                    _tBL_Admin_TypeByModules.CollectionChanged += FixupTBL_Admin_TypeByModules;
                }
                return _tBL_Admin_TypeByModules;
            }
            set
            {
                if (!ReferenceEquals(_tBL_Admin_TypeByModules, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tBL_Admin_TypeByModules != null)
                    {
                        _tBL_Admin_TypeByModules.CollectionChanged -= FixupTBL_Admin_TypeByModules;
                    }
                    _tBL_Admin_TypeByModules = value;
                    if (_tBL_Admin_TypeByModules != null)
                    {
                        _tBL_Admin_TypeByModules.CollectionChanged += FixupTBL_Admin_TypeByModules;
                    }
                    OnNavigationPropertyChanged("TBL_Admin_TypeByModules");
                }
            }
        }
        private TrackableCollection<TBL_Admin_TypeByModules> _tBL_Admin_TypeByModules;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            TBL_Admin_Secciones.Clear();
            TBL_Admin_OpcionesMenu.Clear();
            TBL_Admin_TypeByModules.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupTBL_Admin_Secciones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_Secciones item in e.NewItems)
                {
                    item.TBL_Admin_Modulos = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_Secciones", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_Secciones item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Modulos, this))
                    {
                        item.TBL_Admin_Modulos = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_Secciones", item);
                    }
                }
            }
        }
    
        private void FixupTBL_Admin_OpcionesMenu(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_OpcionesMenu item in e.NewItems)
                {
                    item.TBL_Admin_Modulos = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_OpcionesMenu", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_OpcionesMenu item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Modulos, this))
                    {
                        item.TBL_Admin_Modulos = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_OpcionesMenu", item);
                    }
                }
            }
        }
    
        private void FixupTBL_Admin_TypeByModules(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (TBL_Admin_TypeByModules item in e.NewItems)
                {
                    item.TBL_Admin_Modulos = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("TBL_Admin_TypeByModules", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TBL_Admin_TypeByModules item in e.OldItems)
                {
                    if (ReferenceEquals(item.TBL_Admin_Modulos, this))
                    {
                        item.TBL_Admin_Modulos = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("TBL_Admin_TypeByModules", item);
                    }
                }
            }
        }

        #endregion
    }
}
