//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una plantilla T4 de propiedad de Walter molano.
//     El cambio  de algunas lineas de codigo podran causar comportamientos
//     inesperados de la aplicacion.  Abril 24 de 2012.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core;
using Domain.MainModules.Entities;
using Domain.Core.Specification;
using System.Collections.Generic;

namespace Applcations.MainModule.DocumentLibrary.IServices
{
    public interface ISfTBL_ModuloDocumentosAnexos_CarpetasManagementServices : IGenericServices<TBL_ModuloDocumentosAnexos_Carpetas>
    {
        List<TBL_ModuloDocumentosAnexos_Carpetas> GetFoldersByIdContrato(string IdContrato);

        bool SaveFolder(string idParent, string idcategory, string nombre, string IdContrato, string idUser);

        bool DeleteFolderAndFiles(int idFolder);
    }
}
    